// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/purchase_order_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:frontend/models/api/purchase_order.dart' as _i6;
import 'package:frontend/services/purchase_order_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PurchaseOrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseOrderService extends _i1.Mock
    implements _i3.PurchaseOrderService {
  MockPurchaseOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.FlutterSecureStorage);

  @override
  _i5.Future<List<_i6.PurchaseOrder>> fetchPurchaseOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPurchaseOrders,
          [],
        ),
        returnValue:
            _i5.Future<List<_i6.PurchaseOrder>>.value(<_i6.PurchaseOrder>[]),
      ) as _i5.Future<List<_i6.PurchaseOrder>>);

  @override
  _i5.Future<void> addPurchaseOrder(_i6.PurchaseOrder? po) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPurchaseOrder,
          [po],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePurchaseOrder(_i6.PurchaseOrder? po) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePurchaseOrder,
          [po],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePurchaseOrder(String? purchaseOrderCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePurchaseOrder,
          [purchaseOrderCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Uint8List> downloadFile(String? endpointPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [endpointPath],
        ),
        returnValue: _i5.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i5.Future<_i7.Uint8List>);
}
